### ISSUE TITLE
mongr.no/app/qmongr not working

### ISSUE THREAD

**Issue by arnfinn** [mong/qmongr#177]
Probably because of #176: `qmongr` needs `imongr 0.12` but `hnskde/qmongr-base-r` image is shipped with an older version of `imongr`.

I restarted the latest `qmongr-base-r` Travis job. This will hopefully fix it.

**Comment by arnfinn** [comment]
I tried to rebuild `qmongr_base_r`, hopefully with latest version of `imongr`, but the app is still not working.

Then I did the following to roll back to previous version(s):
1. Forced `qmongr_base_r` to install `imongr v0.11.0` (https://github.com/mong/qmongr-base-r/commit/7733842b6d866be271d2c3ea2947c672647f9a4b)
2. Rebuild [this](https://travis-ci.org/github/mong/qmongr/jobs/725313892) Travis job (version `0.14.2` of `qmongr`) to push a new image of `hnskde/qmongr:release` to Docker hub.

Thus, have to revert https://github.com/mong/qmongr-base-r/commit/7733842b6d866be271d2c3ea2947c672647f9a4b if this bug is fixed.

**Comment by areedv** [comment]
Do work in my dev env:
![image](https://user-images.githubusercontent.com/1522857/94470373-e52d4100-01c7-11eb-9d63-df8d981126a3.png)
Next up for me will be the qmongr-base-r image...

**Comment by areedv** [comment]
Successfully run qmongr as standalone container (as on mongr.no) with the following steps:
1. rebuild qmongr-base-r docker image with v0.12.0 of imongr
2. rebuild qmongr docker image _hnskde/qmongr:test_ with v0.15.1 of qmongr based on (_i.e._ FROM) the above image
3. run above qmongr docker image (´´´run -p 3838:3838 hnskde/qmongr:test```) and pointing a browser to localhost:3838:
![image](https://user-images.githubusercontent.com/1522857/94475564-8b307980-01cf-11eb-866e-61d6868d9c87.png)

Next step will be use of a database rather than built-in data...

**Comment by areedv** [comment]
Successfully run qmongr as above but alongside a database using the following _docker-compose.yml_:
```yaml
 version: '3.6'

services:

  testdb:
    image: mariadb
    restart: "no"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: imongr
      MYSQL_USER: imongr
      MYSQL_PASSWORD: imongr
    volumes:
      - ./imongr_db_dump.sql.gz:/docker-entrypoint-initdb.d/imongr_db_dump.sql.gz

  dev:
    depends_on:
      - testdb
    image: hnskde/qmongr:test
    restart: "no"
    ports:
      - 3838:3838
    dns:
      - 8.8.8.8
    environment:
      PASSWORD: password
      IMONGR_CONTEXT: DEV
      IMONGR_DB_HOST: testdb
      IMONGR_DB_NAME: imongr
      IMONGR_DB_USER: imongr
      IMONGR_DB_PASS: imongr
      IMONGR_ADMINER_URL: http://localhost:8888

  testadminer:
    depends_on:
      - testdb
    image: adminer
    restart: "no"
    environment:
      ADMINER_PLUGINS: frames
    ports:
      - 8888:8080
```
![image](https://user-images.githubusercontent.com/1522857/94479815-a0a8a200-01d5-11eb-81bf-a08c7e7d7c2d.png)

I still do not see why this should not work at mongr.no...

Next step will be to re-deploy qmongr v0.15.1 and imongr v0.12.0 at mongr.no and look into any log entries both from shinyproxy and from within qmongr containers at the nodes. Not tonight, though...
